### ISSUE TITLE
CI fails to compile warp on nightly

### ISSUE THREAD

**Issue by joshrotenberg** [rust-lang/mdBook#1610]
It looks like this just broke with my latest PR #1609.

```
2021-07-25T04:20:25.4471251Z    Compiling mdbook v0.4.10 (/home/runner/work/mdBook/mdBook)
2021-07-25T04:20:26.6098316Z error: internal compiler error: unexpected concrete region in borrowck: ReStatic
2021-07-25T04:20:26.6100888Z    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.2.5/src/filters/sse.rs:457:5
2021-07-25T04:20:26.6101788Z     |
2021-07-25T04:20:26.6102332Z 457 | /     pub fn stream<S>(
2021-07-25T04:20:26.6102852Z 458 | |         self,
2021-07-25T04:20:26.6103446Z 459 | |         event_stream: S,
2021-07-25T04:20:26.6104202Z 460 | |     ) -> impl TryStream<
2021-07-25T04:20:26.6104739Z ...   |
2021-07-25T04:20:26.6105202Z 476 | |         }
2021-07-25T04:20:26.6105650Z 477 | |     }
2021-07-25T04:20:26.6106123Z     | |_____^
2021-07-25T04:20:26.6106573Z     |
2021-07-25T04:20:26.6107310Z     = note: delayed at compiler/rustc_mir/src/borrow_check/region_infer/opaque_types.rs:87:44
2021-07-25T04:20:26.6109444Z 
2021-07-25T04:20:26.6110050Z error: internal compiler error: unexpected concrete region in borrowck: ReStatic
2021-07-25T04:20:26.6111348Z    --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/warp-0.2.5/src/filters/sse.rs:492:1
2021-07-25T04:20:26.6112028Z     |
2021-07-25T04:20:26.6112337Z 492 | / pub fn keep<S>(
2021-07-25T04:20:26.6112725Z 493 | |     event_stream: S,
2021-07-25T04:20:26.6113188Z 494 | |     keep_interval: impl Into<Option<Duration>>,
2021-07-25T04:20:26.6113816Z 495 | | ) -> impl TryStream<
2021-07-25T04:20:26.6114164Z ...   |
2021-07-25T04:20:26.6114458Z 514 | |     }
2021-07-25T04:20:26.6114737Z 515 | | }
2021-07-25T04:20:26.6115038Z     | |_^
2021-07-25T04:20:26.6115300Z     |
2021-07-25T04:20:26.6115863Z     = note: delayed at compiler/rustc_mir/src/borrow_check/region_infer/opaque_types.rs:87:44
2021-07-25T04:20:26.6116329Z 
2021-07-25T04:20:26.6117187Z thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1050:13
2021-07-25T04:20:26.6118109Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2021-07-25T04:20:26.6118559Z 
2021-07-25T04:20:26.6118994Z error: internal compiler error: unexpected panic
2021-07-25T04:20:26.6119364Z 
2021-07-25T04:20:26.6119840Z note: the compiler unexpectedly panicked. this is a bug.
2021-07-25T04:20:26.6120209Z 
2021-07-25T04:20:26.6121211Z note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
2021-07-25T04:20:26.6122088Z 
2021-07-25T04:20:26.6122890Z note: rustc 1.56.0-nightly (d9aa28767 2021-07-24) running on x86_64-unknown-linux-gnu
2021-07-25T04:20:26.6123335Z 
2021-07-25T04:20:26.6124038Z note: compiler flags: -C embed-bitcode=no -C debuginfo=2 --crate-type lib
2021-07-25T04:20:26.6124490Z 
2021-07-25T04:20:26.6124937Z note: some of the compiler flags provided by cargo are hidden
2021-07-25T04:20:26.6125317Z 
2021-07-25T04:20:26.6125659Z query stack during panic:
2021-07-25T04:20:26.6126064Z end of query stack
2021-07-25T04:20:26.6219637Z error: could not compile `warp`
```

See https://github.com/rust-lang/mdBook/pull/1609/checks?check_run_id=3153268133

**Comment by ehuss** [comment]
Filed the issue upstream at https://github.com/rust-lang/rust/issues/87455.

It may be fixed relatively soon, the regression is only a couple days old.  We can wait, or alternatively it looks like warp 0.3 does not have this problem, so perhaps updating would be best.

**Comment by joshrotenberg** [comment]
Looking into updating on our end now.
