### ISSUE TITLE
Bug: Preprocessor failure returns a status code of 0

### ISSUE THREAD

**Issue by markmandel** [rust-lang/mdBook#1872]
Context:

I have `mdbook build` running through my CI system so that we can test if the documentation builds, and links exist, etc.

I recently realised that the documentation was failing to build, because the preprocessor was failing, but since it didn't affect the subsequent tests it was passing and went unnoticed for a while.

Logs:

```shell
➜  docs git:(main) mdbook build
2022-08-08 17:55:52 [INFO] (mdbook::book): Book building has started
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', src/main.rs:121:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-08-08 17:56:11 [INFO] (mdbook::book): Running the html backend
➜  docs git:(main) echo $?
0
➜  docs git:(main) ./preprocessor.sh
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', src/main.rs:121:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
➜  docs git:(main) echo $?
101
```

As you can see above, my `preprocessor.sh` (which is the preprocessor) fails when executing directly, and if run on it's own returns a status of 101.

But when run through mdbook, it exits with a 0 as if nothing failed at all.

I'd love it if `mdbook build` returned a non-zero error code on preprocessor failure.

**Comment by ehuss** [comment]
Mdbook will return an error if the preprocessor fails when doing the preprocess step. However, it doesn't fail during the "supports" step. Unfortunately the preprocessor API can't distinguish between "the preprocessor supports a given renderer" and "the preprocessor crashed".  It only knows that a non-zero exit code means the renderer isn't supported.

I think ideally a more sophisticated interface would help here (such as requiring the preprocessor to return some structured message on stdout to positively indicate that it supports the renderer).

**Comment by markmandel** [comment]
> I think ideally a more sophisticated interface would help here (such as requiring the preprocessor to return some structured message on stdout to positively indicate that it supports the renderer).

That would work too!

**Comment by kraftnix** [comment]
It would be really useful if this was at least configurable that any non-zero exit code from a preprocessor can cause the whole build to fail.

Similar to the reporter of the issue, this can cause very unexpected behaviour in CI when the build exits successfully but can generate a wrong/broken site.
